### ISSUE TITLE
The entire code base should use nint/nuint instead of IntPtr/UIntPtr

### ISSUE THREAD

**Issue by aybe** [aybe/imgui.NET#8]
Currently, even if using type maps, CppSharp ends up resolving the formers to the latters.

**Comment by ds5678** [comment]
In C#11 and later, this makes no difference. `nint` is an alias for `IntPtr` in the exact same way that `int` is an alias for `Int32`.

**Comment by aybe** [comment]
Thank you, I will just live with that fact and move on; porting to it was a pain anyway, I tried and failed.😅
